[workspace]
resolver = "2"
members = [
    "crates/eosio-chain",
    "crates/macro",
    "crates/codegen",
]

exclude = [
    "examples/",
    "tests",
]

[profile.release]
panic = "abort"
lto = true
