[workspace]
resolver = "2"
members = [
    "crates/chain",
    "crates/macro",
    "crates/codegen",
    "crates/chaintester",
]

exclude = [
    "examples/",
    "tests"
]

[profile.release]
panic = "abort"
lto = true
