[workspace]
resolver = "2"
members = [
    "counter",
    "counter2",
    "token",
    "inlineaction",
    "notify/receiver",
    "notify/sender",
    "globalstates",
    "secondaryindex",
    "helloworld",
    "dbi64",
]

exclude = []
