name: PR
on:
  pull_request:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-code-generator:
    strategy:
      matrix:
        python-version: [3.9]
    name: run code generator tests
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache Results
        uses: actions/cache@v2
        id: cache-tests-results
        with:
          path: |
            ~/.cargo
          key: ${{ runner.os }}-tests-code-generator-results-1
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy, rust-src
      - uses: actions/checkout@v2
      - name: test code generator
        working-directory: crates/codegen
        run: |
          cargo test contract_tests::tests::
  tests:
    strategy:
      matrix:
        python-version: [3.9]
    name: run tests in tests
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy, rust-src
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python3 -m pip install -U pip setuptools
          python3 -m pip install wheel
          python3 -m pip install pytest
          python3 -m pip install pytest-xdist
          python3 -m pip install ipyeos
          python3 -m pip install rust-contracts-builder
      - name: Run eos-debugger
        run: |
          PYTHON_SHARED_LIB_PATH=${{ env.pythonLocation }}/lib/libpython3.9.so eos-debugger &
      - name: Install binaryen
        run: |
          set -e
          curl -L https://github.com/WebAssembly/binaryen/releases/download/version_109/binaryen-version_109-x86_64-linux.tar.gz | tar xzf -
          echo "`pwd`/binaryen-version_109/bin" > $GITHUB_PATH
      - name: run unit tests
        working-directory: tests
        run: |
          PYTHON_SHARED_LIB_PATH=${{ env.pythonLocation }}/lib/libpython3.9.so make -j3 -S
      - name: code coverage report
        working-directory: tests
        run: |
          cargo install grcov
          rustup component add llvm-tools-preview
          export CARGO_INCREMENTAL=0
          export RUSTFLAGS="-Cinstrument-coverage -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off"
          TEST_COVERAGE=TRUE cargo +nightly test -- --test-threads=1
          grcov . --binary-path=target/debug -s ../crates/chain -t lcov --llvm --branch --ignore-not-existing -o chain.lcov
          grcov . --binary-path=target/debug -s . -t lcov --llvm --branch --ignore-not-existing -o testall.lcov
          curl -S -f https://codecov.io/bash -o codecov
          chmod +x codecov
          ./codecov -f chain.lcov

  examples:
    strategy:
      matrix:
        python-version: [3.9]
    name: run tests in examples
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy, rust-src
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python3 -m pip install -U pip setuptools
          python3 -m pip install wheel
          python3 -m pip install pytest
          python3 -m pip install pytest-xdist
          python3 -m pip install ipyeos
          python3 -m pip install rust-contracts-builder
      - name: Run eos-debugger
        run: |
          PYTHON_SHARED_LIB_PATH=${{ env.pythonLocation }}/lib/libpython3.9.so eos-debugger &
      - name: Install binaryen
        run: |
          set -e
          curl -L https://github.com/WebAssembly/binaryen/releases/download/version_109/binaryen-version_109-x86_64-linux.tar.gz | tar xzf -
          echo "`pwd`/binaryen-version_109/bin" > $GITHUB_PATH
      - name: run tests in examples
        working-directory: examples
        run: |
          PYTHON_SHARED_LIB_PATH=${{ env.pythonLocation }}/lib/libpython3.9.so make -j3 -S
