name: PR
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  pr:
    strategy:
      matrix:
        python-version: [3.9]
        step: ['test']
        # step: ['lint', 'test:chain']
    name: ${{ matrix.step }}
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python3 -m pip install -U pip setuptools
          python3 -m pip install wheel
          python3 -m pip install pytest
          python3 -m pip install pytest-xdist
          python3 -m pip install ipyeos
      - name: ${{ matrix.step }}
        working-directory: tests
        run: |
          PYTHON_SHARED_LIB_PATH=${{ env.pythonLocation }}/lib/libpython3.9.so ./test-all.sh
